title: 金泉的故事
description: 白天互不相识的孩子们在夜里手牵着手，一次又一次逃离现实的爪。
theme: just-the-docs

url: https://jin-quan-fred.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
