title: 金泉的故事
description: 白天互不相识的孩子们在夜里手牵着手，一次又一次逃离现实的爪。
theme: just-the-docs

url: https://jin-quan-fred.github.io/

aux_links:
  哔哩哔哩: https://space.bilibili.com/1728396266

favicon_ico: "/assets/images/favicon.ico"

defaults:
  - scope:
      path: "posts" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

color_scheme: dblue
